### ISSUE TITLE
GSAP ScrollTrigger integration still required?

### ISSUE THREAD

**Issue by LucaArgentieri** [MilkshakeStudio/nuxt-lenis#2]
[GSAP ScrollTrigger integration](https://github.com/studio-freight/lenis#gsap-scrolltrigger-integration) still required?
I tried without and it works, I would need confirmation.

**Comment by aritradey-CS** [comment]
The ScrollTrigger plugin is a part of the GSAP library and is used to trigger animations on the scroll with just a few lines of code. [It is built on the GSAP and can be used to trigger those intriguing GSAP animations on the scroll with excellent performance, cross-browser compatibility, and support from the GSAP community ](https://blog.logrocket.com/how-to-use-the-gsap-scrolltrigger-plugin-in-react/)[1](https://blog.logrocket.com/how-to-use-the-gsap-scrolltrigger-plugin-in-react/).

The only required option for ScrollTrigger is trigger, which defines which element triggers the scroll interaction. [Importantly, this does not have to be the same element that is animating ](https://www.williamrchase.com/writing/2020-06-07-scrollytelling-with-gsap-scrolltrigger)[2](https://www.williamrchase.com/writing/2020-06-07-scrollytelling-with-gsap-scrolltrigger).

It’s recommended to register ScrollTrigger in your JavaScript to avoid tree-shaking with build tools. [You can get recent CDN Urls from the GSAP Overview in the docs ](https://greensock.com/st-get-started/)[3](https://greensock.com/st-get-started/).

I hope this helps!

**Comment by LucaArgentieri** [comment]
I got my answer [here](https://github.com/studio-freight/lenis/issues/243)

Thank you!

**Comment by Krislunde** [comment]
> I got my answer [here](https://github.com/studio-freight/lenis/issues/243)
> 
> Thank you!

@LucaArgentieri 

That issue no longer exists. What was the answer?
