### ISSUE TITLE
How to integrate nuxt-lenis with GSAP

### ISSUE THREAD

**Issue by Liam-hi** [MilkshakeStudio/nuxt-lenis#4]
According to Clément, it's highly recommended to integrate GSAP with Lenis. Any ideas how?

**Comment by Krislunde** [comment]
@Liam-hi 

What was the solution?

**Comment by Liam-hi** [comment]
Go OG instead 

`<template>
  <slot></slot>
</template>

<script setup>
import Lenis from "@studio-freight/lenis";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { ScrollToPlugin } from "gsap/ScrollToPlugin";

gsap.registerPlugin(ScrollTrigger, ScrollToPlugin);

onMounted(() => {
  const lenis = new Lenis({
    duration: 1.2,
    easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)),
  });

  lenis.on("scroll", ScrollTrigger.update);

  gsap.ticker.add((time) => {
    lenis.raf(time * 1000);
  });

  gsap.ticker.lagSmoothing(0);
});
</script>

<style>
html.lenis {
  height: auto;
}

.lenis.lenis-smooth {
  scroll-behavior: auto;
}

.lenis.lenis-smooth [data-lenis-prevent] {
  overscroll-behavior: contain;
}

.lenis.lenis-stopped {
  overflow: hidden;
}

.lenis.lenis-scrolling iframe {
  pointer-events: none;
}

</style>`

**Comment by Krislunde** [comment]
Alright, thanks! That's what I'm already doing anyway. Was just moseying around nuxt-lenis, to see if it was viable or convenient in any way.

Thanks again for confirming :)

**Comment by LucaMargadant** [comment]
I came across this thread while looking for a recommended approach myself. I like the convenience of using Lenis with a wrapper like nuxt-lenis, so I thought I’d share the solution I ended up with, in case it helps someone else later on:

I use a composable to handle loading and initializing GSAP, and exported there a new function to sync Lenis with ScrollTrigger.

```
let gsap = null;
let ScrollTrigger = false;

export default async () => {
    if (!gsap) {
        const importedGsap = await import('gsap/dist/gsap');
        ScrollTrigger = await import('gsap/dist/ScrollTrigger');
        ScrollTrigger = ScrollTrigger.ScrollTrigger;
        ScrollTrigger.config({ ignoreMobileResize: true });

        gsap = importedGsap.gsap;
        gsap.registerPlugin(ScrollTrigger);
    }
    return {
        gsap,
        ScrollTrigger,
    };
};

export const syncScrollTriggerWithLenis = () => {
    const { lenis } = useLenis('global');

    if (!gsap || !ScrollTrigger) {
        console.warn('gsap or ScrollTrigger is not available');
        return;
    }

    lenis.value.on('scroll', () => {
        ScrollTrigger?.update();
    });

    gsap.ticker.add((time) => {
        lenis.value.raf(time * 1000);
    });

    gsap.ticker.lagSmoothing(0);
};


```

Then, wherever you use the `<Lenis>` component, just call the sync function once it’s initiated.

```
<lenis
  id="global"
  class="__lenis"
  @initiated="syncScrollTriggerWithLenis"
>
  <NuxtPage class="__nuxt-page" />
</lenis>
```
