### ISSUE TITLE
Pre-transform error: Failed to resolve import '.../node_modules/nuxt-lenis/dist/runtime/components/Lenis.vue"

### ISSUE THREAD

**Issue by Aybee5** [MilkshakeStudio/nuxt-lenis#8]
In version `1.2.0` when you try using the `<lenis>` component, I get the Failed to resolve import from './node_modules/nuxt-lenis/dist/runtime/components/Lenis.vue'

Here is a reproduction https://stackblitz.com/edit/nuxt-starter-9jmmdx?file=app.vue

and importing the component also instead of using auto imports results in the error

```
ERROR  Importing directly from module entry-points is not allowed. [importing nuxt-lenis from app.vue]
```

**Comment by Slgoetz** [comment]
Looking into this now.

**Comment by Aybee5** [comment]
Thank you, it works fine now
